language: ruby
rvm:
  - 2.2.4
  - 2.3.1
  - jruby-9.0.5.0
gemfile:
  - gemfiles/rails_5_1.gemfile
bundler_args: --without local
before_install:
  - gem install bundler -v '> 1.5.0'
env:
  RUBY_GC_MALLOC_LIMIT: 90000000
  RUBY_FREE_MIN: 200000
matrix:
  fast_finish: true
